on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  Site-Preloader:
    runs-on:  ubuntu-latest 
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: execute script
        run:
          python preload_site.py

      - name: commit and push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Ran job, updated log"
          git push

